import Head from "next/head";
import { useState } from "react";
import Question from "../components/Question";
import answerModel from "../model/answer";
import questionModel from "../model/question";
import styles from "../styles/pages/Home.module.css";

const teste = new questionModel(20, "melhor", [
  answerModel.wrong("verde"),
  answerModel.wrong("Azul"),
  answerModel.wrong("Amarelo"),
  answerModel.certain("Preto"),
]);

export default function Home() {
  const [question, setQuestion] = useState(teste);

  function handleSelectedAnswer(index: number) {
    const Newquestion = teste.handleAnswerQuestion(index);
    setQuestion(Newquestion);
    console.log(Newquestion.toObject());
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          display: "flex",
          height: "100vh",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Question value={question} onResponse={handleSelectedAnswer} />
      </main>
    </div>
  );
}
