import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import Question from "../components/Question";
import answerModel from "../model/answer";
import questionModel from "../model/question";
import Button from "../components/Button";

const teste = new questionModel(20, "melhor", [
  answerModel.wrong("verde"),
  answerModel.wrong("Azul"),
  answerModel.wrong("Amarelo"),
  answerModel.certain("Preto"),
]);

export default function Home() {
  const [question, setQuestion] = useState(teste);
  const questionRef = useRef<questionModel>();

  useEffect(() => {
    questionRef.current = question;
    return () => {};
  }, [question]);

  function handleSelectedAnswer(index: number) {
    const Newquestion = question.handleAnswerQuestion(index);
    setQuestion(Newquestion);
  }

  function handleTimefinished() {
    if (!questionRef.current.HandleAnswer) {
      setQuestion(question.handleAnswerQuestion(-1));
    }
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          display: "flex",
          height: "100vh",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Question
          duration={5}
          value={question}
          onResponse={handleSelectedAnswer}
          timefinished={handleTimefinished}
        />
        <Button text="próxima Questão" href="/resultado" />
      </main>
    </div>
  );
}
